# -*- coding: utf-8 -*-
"""TPOT1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1doQWKX6jUOrasZ0AmMWBiTlL69rhbJN3

[TPOT tutorial](https://machinelearningmastery.com/tpot-for-automated-machine-learning-in-python/)
"""

pip install tpot

import numpy as np
import pandas as pd #import pandas
from tpot import TPOTClassifier
from sklearn.model_selection import RepeatedStratifiedKFold ,train_test_split
from sklearn.preprocessing import LabelEncoder

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv('/content/drive/MyDrive/breast-cancer-wisconsin.data.txt')
df.replace('?',-99999, inplace=True)
df.drop(['id'], 1, inplace=True)
X = np.array(df.drop(['class'], 1))
X = X.astype('float32')
y = np.array(df['class'])
y = LabelEncoder().fit_transform(y.astype(str))
# Look at the dataset again
print(f'Number of Rows: {df.shape[0]}')
print(f'Number of Columns: {df.shape[1]}')
print(df.head())

"""# TPOP USING CV"""

# define model evaluation
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
tpot = TPOTClassifier(generations=5, population_size=50, cv=cv, scoring='accuracy', verbosity=2, random_state=1, n_jobs=-1)
tpot.fit(X, y)
tpot.export('bestmodel1.py')

"""# TPOT USING TRAIN/TEST"""

seed = 42
test_size = 0.2
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=test_size, random_state=seed)
tpot = TPOTClassifier(generations=5, population_size=50, scoring='accuracy', verbosity=2, random_state=1, n_jobs=-1)
tpot.fit(X_train, y_train)
print(tpot.score(X_test, y_test))
tpot.export('bestmodel.py')